### ISSUE TITLE
Date and time related icons should be set.

### ISSUE THREAD

**Issue by rabiul0420** [magepeopleteam/mage-eventpress#3]
![Picture1](https://github.com/magepeopleteam/mage-eventpress/assets/30313066/e5e5b736-a3f2-4bb7-a886-cb71f5183e65)

**Comment by aamahin** [comment]
Done

**Comment by rabiul0420** [comment]
Okay, Thanks.

**Comment by rabiul0420** [comment]
Okay, Thanks.
